
kind: ImageStream
apiVersion: v1
metadata:
  name: s2i-angular-nginx
  creationTimestamp: 
spec:
  dockerImageRepository: myproject/s2i-angular-nginx
  tags:
  - name: latest
    annotations:
      description: Build Angular apps with CLI and run them with nginx:latest
      iconClass: icon-angularjs
      supports: angular,angular:1
      tags: builder,angular,nginx
      version: '1'
    from:
      kind: ImageStreamTag
      name: s2i-angular-nginx:latest
---
kind: BuildConfig
apiVersion: "v1"
metadata:
  name: s2i-angular-nginx
triggers:
  - type: ConfigChange
  - github:
      secret: 5e2c820db87f67d7
    type: GitHub
spec:
  source:
    type: Git
    git:
      uri: https://github.com/klmcwhirter/s2i-angular-nginx.git
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: s2i-angular-nginx:latest
